backend:
  name: github
  repo: PireJoseph/gridsome-portfolio

media_folder: "static/uploads"
public_folder: "/uploads"


collections:

  - name: "techs"
    label: "Techs"
    folder: "content/techs"
    create: true
    identifier_field: "id"
    fields:
      - {label: "Id", name: "id", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Url", name: "url", widget: "string", required: false }
      - {label: "Logo", name: "logo", widget: "image"}
      - {label: "Color", name: "color", widget: "string", required: false}

  - name: "projects"
    label: "Projects"
    folder: "content/projects"
    create: true
    identifier_field: "id"
    fields:
      - {label: "Id", name: "id", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "ShortDescription", name: "shortDescription", widget: "text"}
      - {label: "Banner", name: "banner", widget: "image",  required: false}
      - {label: "Status", name: "status", widget: "string"}
      - {label: "CreatedAt", name: "createdAt", widget: "datetime"}
      - {label: "Techs", name: "techs", widget: "relation", collection: "techs", valueField: "title", searchFields: ["title"], multiple: true}
      - {label: "Skills", name: "skills", widget: "relation", collection: "skills", valueField: "title", searchFields: ["title"], multiple: true, required: false}

  - name: "skills"
    label: "Skills"
    folder: "content/skills"
    create: true
    identifier_field: "id"
    fields:
      - {label: "Id", name: "id", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Color", name: "color", widget: "string", required: false}


  - name: "certifications"
    label: "Certifications"
    folder: "content/certifications"
    create: true
    identifier_field: "id"
    fields:
      - {label: "Id", name: "id", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Provider", name: "provider", widget: "string"}
      - {label: "AcquiredAt", name: "acquiredAt", widget: "datetime"}

  - name: "diplomas"
    label: "Diplomas"
    folder: "content/diplomas"
    create: true
    identifier_field: "id"
    fields:
      - {label: "Id", name: "id", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Provider", name: "provider", widget: "string"}
      - {label: "Provider Logo", name: "providerLogo", widget: "image", required: false}
      - {label: "AcquiredAt", name: "acquiredAt", widget: "datetime"}

  - name: "languages"
    label: "Languages"
    folder: "content/languages"
    create: true
    identifier_field: "id"
    fields:
      - {label: "Id", name: "id", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Iso", name: "iso", widget: "string"}
      - {label: "Flag", name: "flag", widget: "image"}
      - {label: "Level", name: "level", widget: "string"}

  - name: "interests"
    label: "Interests"
    folder: "content/interests"
    create: true
    identifier_field: "id"
    fields:
      - {label: "Id", name: "id", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text", required: false}

  - name: "jobs"
    label: "Jobs"
    folder: "content/jobs"
    create: true
    identifier_field: "id"
    fields:
      - {label: "Id", name: "id", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Started At", name: "startedAt", widget: "datetime"}
      - {label: "Ended At", name: "endedAt", widget: "datetime"}
      - {label: "Employer", name: "employer", widget: "string"}
      - {label: "Techs", name: "techs", widget: "relation", collection: "techs", valueField: "title", searchFields: ["title"], multiple: true}
      - {label: "Skills", name: "skills", widget: "relation", collection: "skills", valueField: "title", searchFields: ["title"], multiple: true, required: false}