backend:
  name: github
  repo: PireJoseph/gridsome-portfolio
  branch: dev

media_folder: "static/uploads"
public_folder: "/uploads"


collections:

  - name: "techs"
    label: "Techs"
    folder: "content/techs"
    create: true
    extension: 'md'
    fields:
      - {label: "Id", name: "id", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "ShortDescription", name: "shortDescription", widget: "text"}
      - {label: "Url", name: "url", widget: "string", required: false }
      - {label: "Logo", name: "logo", widget: "image"}
      - {label: "Featured", name: "featured", widget: "boolean", default: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "projects"
    label: "Projects"
    folder: "content/projects"
    create: true
    fields:
      - {label: "Id", name: "id", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "ShortDescription", name: "shortDescription", widget: "text"}
      - {label: "Banner", name: "banner", widget: "image",  required: false}
      - {label: "Status", name: "status", widget: "string"}
      - {label: "CreatedAt", name: "createdAt", widget: "datetime"}
      - {label: "Featured", name: "featured", widget: "boolean", default: false}
      - {label: "On Resume", name: "onResume", widget: "boolean", default: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Techs", name: "techs", widget: "relation", collection: "techs", valueField: "id", displayFields: ["title"], searchFields: ["title"], multiple: true, required: false}
      - {label: "Skills", name: "skills", widget: "relation", collection: "skills", valueField: "id", displayFields: ["title"], searchFields: ["title"], multiple: true, required: false}

  - name: "skills"
    label: "Skills"
    folder: "content/skills"
    create: true
    fields:
      - {label: "Id", name: "id", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Short Name", name: "shortName", widget: "string"}
      - {label: "ShortDescription", name: "shortDescription", widget: "text"}
      - {label: "Featured", name: "featured", widget: "boolean", default: false}
      - {label: "On Resume", name: "onResume", widget: "boolean", default: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Techs", name: "techs", widget: "relation", collection: "techs", valueField: "id", displayFields: ["title"], searchFields: ["title"], multiple: true, required: false}


  - name: "certifications"
    label: "Certifications"
    folder: "content/certifications"
    create: true
    fields:
      - {label: "Id", name: "id", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "ShortDescription", name: "shortDescription", widget: "text"}
      - {label: "Provider", name: "provider", widget: "string"}
      - {label: "Provider Logo", name: "providerLogo", widget: "image", required: false}
      - {label: "AcquiredAt", name: "acquiredAt", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}


  - name: "diplomas"
    label: "Diplomas"
    folder: "content/diplomas"
    create: true
    fields:
      - {label: "Id", name: "id", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "ShortDescription", name: "shortDescription", widget: "text"}
      - {label: "Provider", name: "provider", widget: "string"}
      - {label: "Provider Logo", name: "providerLogo", widget: "image", required: false}
      - {label: "AcquiredAt", name: "acquiredAt", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "languages"
    label: "Languages"
    folder: "content/languages"
    create: true
    fields:
      - {label: "Id", name: "id", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Iso", name: "iso", widget: "string"}
      - {label: "Flag", name: "flag", widget: "image"}
      - {label: "Level", name: "level", widget: "string"}

  - name: "interests"
    label: "Interests"
    folder: "content/interests"
    create: true
    fields:
      - {label: "Id", name: "id", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "ShortDescription", name: "shortDescription", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "jobs"
    label: "Jobs"
    folder: "content/jobs"
    create: true
    fields:
      - {label: "Id", name: "id", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "ShortDescription", name: "shortDescription", widget: "text"}
      - {label: "Started At", name: "startedAt", widget: "datetime"}
      - {label: "Ended At", name: "endedAt", widget: "datetime"}
      - {label: "Employer", name: "employer", widget: "string"}
      - {label: "Employer Logo", name: "employerLogo", widget: "image", required: true}
      - {label: "Location", name: "location", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Techs", name: "techs", widget: "relation", collection: "techs", valueField: "id", displayFields: ["title"], searchFields: ["title"], multiple: true, required: false}
      - {label: "Skills", name: "skills", widget: "relation", collection: "skills", valueField: "id", displayFields: ["title"], searchFields: ["title"], multiple: true, required: false}