backend:
  name: github
  repo: PireJoseph/gridsome-portfolio


media_folder: "static/uploads"
public_folder: "/uploads"


collections:

  - name: "techs"
    label: "Techs"
    folder: "content/techs"
    create: true
    identifier_field: "name"
    valueField: "name"
    slug: "{{tech_name}}"
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "Url", name: "url", widget: "string"}
      - {label: "Logo", name: "logo", widget: "image"}
      - {label: "Banner", name: "banner", widget: "image"}
      - {label: "Color", name: "color", widget: "string"}

  - name: "people"
    label: "People"
    folder: "content/people"
    create: true
    identifier_field: "name"
    valueField: "name"
    slug: "{{slug}}"
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Github", name: "github", widget: "string"}
      - {label: "LinkedIn", name: "linkedIn", widget: "string"}
      - {label: "Twitter", name: "twitter", widget: "string"}
      - {label: "Facebook", name: "facebook", widget: "string"}
      - {label: "Website", name: "website", widget: "string"}

  - name: "categories"
    label: "Categories"
    folder: "content/categories"
    create: true
    identifier_field: "name"
    valueField: "name"
    slug: "{{slug}}"
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Color", name: "color", widget: "string"}

  - name: "projects"
    label: "Projects"
    folder: "content/projects"
    create: true
    identifier_field: "name"
    valueField: "name"
    slug: "{{slug}}"
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "ShortDescription", name: "shortDescription", widget: "markdown"}
      - {label: "Banner", name: "banner", widget: "image"}
      - {label: "Status", name: "status", widget: "string"}
      - {label: "CreatedAt", name: "createdAt", widget: "datetime"}
      - {label: "Category", name: "category", widget: "image"}
      - {label: "Tools", name: "tools", widget: "relation", collection: "techs", valueField: "name", searchFields: ["name"], multiple: true}
      - {label: "Collaborators", name: "collaborators", widget: "relation", collection: "people", valueField: "name", searchFields: ["name"], multiple: true}
      - {label: "Tags", name: "categories", widget: "relation", collection: "categories", valueField: "name", searchFields: ["name"], multiple: true}

  - name: "skills"
    label: "Skills"
    folder: "content/skills"
    create: true
    identifier_field: "category_name"
    valueField: "category_name"
    slug: "{{slug}}"
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Color", name: "color", widget: "string"}

  - name: "certifications"
    label: "Certifications"
    folder: "content/certifications"
    create: true
    identifier_field: "title"
    valueField: "title"
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "Provider", name: "provider", widget: "string"}
      - {label: "AcquiredAt", name: "acquiredAt", widget: "datetime"}

  - name: "diplomas"
    label: "Diplomas"
    folder: "content/diplomas"
    create: true
    identifier_field: "title"
    valueField: "title"
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "Provider", name: "provider", widget: "string"}
      - {label: "AcquiredAt", name: "acquiredAt", widget: "datetime"}

  - name: "languages"
    label: "Languages"
    folder: "content/languages"
    create: true
    identifier_field: "title"
    valueField: "title"
    slug: "{{slug}}"
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Iso", name: "iso", widget: "string"}
      - {label: "Flag", name: "flag", widget: "image"}

  - name: "interests"
    label: "Interests"
    folder: "content/interests"
    create: true
    identifier_field: "title"
    valueField: "title"
    slug: "{{slug}}"
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Description", name: "description", widget: "markdown"}

  - name: "jobs"
    label: "Jobs"
    folder: "content/jobs"
    create: true
    identifier_field: "title"
    valueField: "title"
    slug: "{{slug}}"
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "Started At", name: "startedAt", widget: "datetime"}
      - {label: "Ended At", name: "endedAt", widget: "datetime"}
      - {label: "Employer", name: "employer", widget: "string"}